### PR TITLE
Latest mitogen

### PR DESCRIPTION
**Pull request by guenhter**
Add Alpine 3.20 image, update some minor ansible versions and update the mitogen version to 0.3.11 which supports now ansible 10 (Core 2.17).

### CODE REVIEW

**Comment by guenhter** [comment]
Resloves https://github.com/willhallonline/docker-ansible/issues/82

**Comment by guenhter** [comment]
It was not a lot of work so I have no problem with it to redo this upgrade when you've finished with your issue.

**Comment by willhallonline** [comment]
@guenhter , if you want to re-roll this against master. There are a couple of changes, but keen to still used the PR if possible.

**Comment by guenhter** [comment]
Done.

**Comment by willhallonline** [comment]
@guenhter mitogen install doesn't seem to be working (tried pipx, pip + pip3 from both CI and local machine) - I can't work out why, but have removed from ubuntu 24.04 as seems to be bad. It seems to work with `python3-mitogen` but that is tied to the ubuntu package which is limited to 0.3.7-2 

Will leave as is until it works as designed. Not sure if it is an issue with python 3.12.

**Comment by guenhter** [comment]
Thanks. I also will have a look.

**Pull request merged**
